---
title: "The Midterm Project of Thunder, Team 2"
output: html_document
date: "2022-10-21"
---

### Load Data

```{r}
midterm = data.frame(read.csv("dataset/train.csv"))
midterm2 = subset(midterm, Month=="January")

midterm2_subset <- midterm2[ , names(midterm2) %in% c("ID", "Name", "Age", "Annual_Income", "Num_Bank_Accounts", "Num_Credit_Card", "Interest_Rate", "Num_of_Loan", "Num_of_Delayed_Payment", "Credit_Mix", "Total_EMI_per_month", "Monthly_Balance", "Credit_Score")]
str(midterm2_subset)
```

### Data Cleaning

```{r Upmanyu}
# midterm2_subset =
library('dplyr')
library('purrr')
library('tidyr')
library("stringr")
```

```{r Brooklyn}
# "Age"
# Removed Special Characters & Changed the data type into "int"
midterm2_subset$Age <- gsub("[[:punct:]]", "", midterm2_subset$Age)
midterm2_subset$Age <- as.integer(midterm2_subset$Age)

# "Annual_Income"
# Removed Special Characters & Changed the data type into "num" & Rounded
midterm2_subset$Annual_Income <- gsub("[[:punct:]]", "", midterm2_subset$Annual_Income)
midterm2_subset$Annual_Income <- as.numeric(midterm2_subset$Annual_Income)
midterm2_subset$Annual_Income <- round(midterm2_subset$Annual_Income, digits = 2)
```

```{r HaeLee}
# "Num_of_Loan" 
# Removed Special Characters & Changed the data type from "char" to "int"
midterm2_subset$Num_of_Loan <- gsub("[[:punct:]]", "", midterm2_subset$Num_of_Loan)
midterm2_subset$Num_of_Loan <- as.integer(midterm2_subset$Num_of_Loan)

# "Num_of_Delayed_Payment"
# Removed Special Characters & Changed the data type from "char" to "int"
midterm2_subset$Num_of_Delayed_Payment <- gsub("[[:punct:]]", "", midterm2_subset$Num_of_Delayed_Payment)
midterm2_subset$Num_of_Delayed_Payment <- as.integer(midterm2_subset$Num_of_Delayed_Payment)

# "Num_of_Loan"
# Removed value below 0 
midterm2_subset <- midterm2_subset[midterm2_subset['Num_of_Loan'] >= 0, ]
```

```{r Upmanyu}
# "Credit_Mix"
# Removed Special Characters 
# Converted "char" into "int" from "Good" to 3, "Standard" to 2, and "Bad" to 1
midterm2_subset <- midterm2_subset[midterm2_subset['Credit_Mix'] != "_",]
midterm2_subset$Credit_Mix[midterm2_subset$Credit_Mix == 'Bad'] <- 1
midterm2_subset$Credit_Mix[midterm2_subset$Credit_Mix == 'Standard'] <- 2
midterm2_subset$Credit_Mix[midterm2_subset$Credit_Mix == 'Good'] <- 3
midterm2_subset$Credit_Mix <- as.integer(midterm2_subset$Credit_Mix)
```

```{r Sudhanshu}
# Rounded "Total_EMI_per_month"
midterm2_subset["Total_EMI_per_month"] <- 
round(midterm2_subset["Total_EMI_per_month"], digits = 2)

# "Monthly_Balance"
# Converted into "int" and rounded 
midterm2_subset$Monthly_Balance <- as.integer(midterm2_subset$Monthly_Balance)
midterm2_subset["Monthly_Balance"] <- round(midterm2_subset["Monthly_Balance"], digits = 2)

# "Credit_score"
# Removed Special Characters
# Converted "char" into "int" from "Good" to 3, "Standard" to 2, and "Bad" to 1
midterm2_subset <- midterm2_subset[midterm2_subset['Credit_Score'] != "_",]
midterm2_subset$Credit_Score[midterm2_subset$Credit_Score == 'Poor'] <- 1
midterm2_subset$Credit_Score[midterm2_subset$Credit_Score == 'Standard'] <- 2
midterm2_subset$Credit_Score[midterm2_subset$Credit_Score == 'Good'] <- 3
midterm2_subset$Credit_Score <- as.integer(midterm2_subset$Credit_Score)
```

```{r Upmanyu}
# Removed NA from data
midterm2_subset = na.omit(midterm2_subset)
# Filtered out a group age under 18
midterm2_subset<-midterm2_subset[!(midterm2_subset$Age < 18),]
```

### Discriptive Statistics

```{r}
summary(midterm2_subset)
str(midterm2_subset)
```

### EDA

```{r Brooklyn}
# EDA for Credit Mix

```

```{r Upmanyu}
# EDA for Number of Loan

```

```{r HaeLee}
# EDA for Number of Delayed Payment

## Removed Outliers
library(ezids)
midterm2_subset$Credit_Score = as.factor(midterm2_subset$Credit_Score)
df=outlierKD2(midterm2_subset, Num_of_Delayed_Payment, TRUE, FALSE, FALSE, FALSE)
# summary(df)
# nrow(df)

## Separated three subsets for poor, standard, and good in Credit Score
Poor = subset(df, df$Credit_Score == 1)
Standard = subset(df, df$Credit_Score == 2)
Good = subset(df, df$Credit_Score == 3)

## T-test at 0.95 Confidence Level
# Construct t-intervals for the Number of Delayed Payment
delay_All = t.test(x=df$Num_of_Delayed_Payment)
delay_All
delay_Poor = t.test(x=Poor$Num_of_Delayed_Payment)
delay_Poor
delay_Standard = t.test(x=Standard$Num_of_Delayed_Payment)
delay_Standard
delay_Good = t.test(x=Good$Num_of_Delayed_Payment)
delay_Good
# Result: All are rejected since p-value are below 0.05, which means that each true mean is not equal to 0.

## Check for normality on the Number of Delayed Payment, a numerical variable
library(ggplot2)

## Boxplot
ggplot(df, aes(x=Credit_Score, y=Num_of_Delayed_Payment)) + geom_boxplot( colour=c("red","yellow","green")) +
  labs(title="Boxpot of the Number of Delayed Payment with different Credit Scores", x="Credit Score", y = "Number of Delayed Payment")

## Histogram
# All Groups
ggplot(df, aes(Num_of_Delayed_Payment)) + geom_histogram(fill="red") + ggtitle("Histogram of the Number of Delayed Payment") 
# Poor Group
ggplot(Poor, aes(Num_of_Delayed_Payment)) + geom_histogram(fill="red") + ggtitle("Histogram of the Number of Delayed Payment in Poor Credit Score Group") 
# Standard Group
ggplot(Standard, aes(Num_of_Delayed_Payment)) + geom_histogram(fill="yellow") + ggtitle("Histogram of Number of Delayed Payment in Standard Credit Score Group") 
# Good Group
ggplot(Good, aes(Num_of_Delayed_Payment)) + geom_histogram(fill="green") + ggtitle("Histogram of Number of Delayed Payment in Good Credit Score Group") 

## QQ plot with QQ line
# All Group
qqnorm(df$Num_of_Delayed_Payment, col="red", main="QQ plot of the Number of Delayed Payment")
# Poor Group
qqnorm(Poor$Num_of_Delayed_Payment, col="red", main="QQ plot of the Number of Delayed Payment in Poor Credit Score Group")
qqline(Poor$Num_of_Delayed_Payment)
# Standard Group
qqnorm(Poor$Num_of_Delayed_Payment, col="yellow", main="QQ plot of the Number of Delayed Payment in Standard Credit Score Group")
qqline(Poor$Num_of_Delayed_Payment)
# Good Group
qqnorm(Poor$Num_of_Delayed_Payment, col="green", main="QQ plot of the Number of Delayed Payment in Good Credit Score Group")
qqline(Poor$Num_of_Delayed_Payment)

## ANOVA
# Does the three subgroups have different the Number of Delayed Payment average?
anova_delayed = aov(Num_of_Delayed_Payment ~ Credit_Score, data=df)
anova_delayed
names(anova_delayed)
xkabledply(anova_delayed, title = "ANOVA result summary the Number of Delayed Payment between Credit Score")
# Result: P-value is below 0.05 and reject the Null. Therefore, we can say that credit scores from three different group are significantly different from others and have not same average number of delayed payment."

## Post-hoc Tukey HSD
# Since they are not all the same, we need to follow up with a post-hoc test.
tukeyAoV <- TukeyHSD(anova_delayed)
tukeyAoV
# Result: As we visually observed from box plots, now confirmed with the turkey results, treatment 1, 2, and 3 are pairwise considered having significantly different means at 0.05 level.

# χ2 – test of Independence 
# construct a contingency table between two categorical variables in HW6.

```

```{r Sudhanshu}
# EDA for Total EMI

```

